import "@/styles/globals.css";
import Head from "next/head";
import * as styles from "@/styles/App.module.css";
import Link from "next/link";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header>
          <Link href="/">
            <img className={styles.title} src="/title.png" />
          </Link>
        </header>
        <Component {...pageProps} />
        <footer>
          <img className={styles.present} src="/present.png" />
        </footer>
      </div>
    </>
  );
}
